[build]
default-target = "armv7-unknown-linux-gnueabihf"

[target.armv7-unknown-linux-gnueabihf]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update",
    "apt-get install --assume-yes libasound2-dev:$CROSS_DEB_ARCH",
    "apt-get install --assume-yes libudev-dev:$CROSS_DEB_ARCH",
]